name: Check PR

on:
  pull_request:
    paths-ignore:
      - '!.github/**'
    types:
      - opened
      - synchronize
      - reopened

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          persist-credentials: false
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install
        working-directory: ./tools

      - name: Check PR
        id: run-check-pr
        run: |
          npm run check-pr
          echo ${{ github.event.number }} > ../pr_number
        working-directory: ./tools

      - uses: actions/upload-artifact@v2
        with:
          name: changes
          path: |
            check_pr_output
            pr_number
